# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='img',
            field=models.ImageField(upload_to=b'media/image/uploads_category/', verbose_name='Ico'),
        ),
    ]
