# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-16 07:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20160316_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='img',
            field=models.ImageField(upload_to=b'media/image/uploads_provider/', verbose_name='\u041b\u043e\u0433\u043e'),
        ),
    ]
