# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True, verbose_name='\u041d\u043e\u043c\u0435\u0440 \u0442\u0440\u0430\u043d\u0437\u0430\u043a\u0446\u0438\u0438')),
                ('status', models.CharField(choices=[(b'success', '\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'), (b'canceled', '\u041e\u0442\u043c\u0435\u043d\u0435\u043d\u043e'), (b'revert', '\u0412\u043e\u0437\u0432\u0440\u0430\u0442')], max_length=50, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81 \xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb7\xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8')),
                ('amount', models.IntegerField(verbose_name='\u0421\u0443\u043c\u043c\u0430 \u043f\u043b\u0430\u0442\u0435\u0436\u0430')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('props', models.IntegerField(verbose_name='\u0420\u0435\u043a\u0432\u0438\u0437\u0438\u0442')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Providers', to_field=b'account', verbose_name=b'\xd0\x9b/\xd0\xa1 \xd0\xbf\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xb9\xd0\xb4\xd0\xb5\xd1\x80\xd0\xb0')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile', to_field=b'account', verbose_name=b'\xd0\x9b/\xd0\xa1 \xd0\xbf\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8f')),
            ],
        ),
    ]
