# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='status',
            field=models.CharField(choices=[(b'success', '\u041e\u043f\u043b\u0430\u0447\u0435\u043d\u043e'), (b'canceled', '\u041e\u0442\u043c\u0435\u043d\u0435\u043d\u043e'), (b'revert', '\u0412\u043e\u0437\u0432\u0440\u0430\u0442'), (b'wait', '\u041e\u0436\u0438\u0434\u0430\u0435\u0442')], default=b'wait', max_length=50, verbose_name=b'\xd0\xa1\xd1\x82\xd0\xb0\xd1\x82\xd1\x83\xd1\x81 \xd1\x82\xd1\x80\xd0\xb0\xd0\xbd\xd0\xb7\xd0\xb0\xd0\xba\xd1\x86\xd0\xb8\xd0\xb8'),
        ),
    ]
