# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 11:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment_messages', '0004_auto_20160425_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name=b'\xd0\x9f\xd0\xbe\xd0\xbb\xd1\x8c\xd0\xb7\xd0\xbe\xd0\xb2\xd0\xb0\xd1\x82\xd0\xb5\xd0\xbb\xd1\x8c'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payments.Providers', verbose_name=b'\xd0\x9f\xd1\x80\xd0\xbe\xd0\xb2\xd0\xb0\xd0\xb9\xd0\xb4\xd0\xb5\xd1\x80'),
        ),
    ]
