# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-27 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_messages', '0005_auto_20160427_1743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='title',
        ),
    ]
